import type { LetterGroup } from "./types";
export const group02: LetterGroup = {
  num:"02", name:"Jeem, Ha, Kha", label:"JEEM GROUP", trait:"Deep bowl shapes", available:false,
  letters: [
    { arabic:"ج", name:"Jeem", roman:"j", detail:{ arabicName:"جيم", globalIndex:5, nibAngle:"40°", about:"Jeem has a distinctive bowl shape with a dot below. One of the more challenging letters, its deep curve requires confident and uninterrupted pen control.", strokes:["Start from the upper right with a curved entry stroke","Sweep down and to the left into a deep bowl","The bowl curves left then upward to form the body","Exit with a descending tail sweeping below the baseline","Place a single dot precisely below the body's center"], proportionTip:"The descender drops approximately 3 rhombic dots below the baseline. The bowl's width equals about 4 dots.", forms:{isolated:"ج",initial:"جـ",medial:"ـجـ",final:"ـج"} }},
    { arabic:"ح", name:"Ha", roman:"ḥ", detail:{ arabicName:"حاء", globalIndex:6, nibAngle:"40°", about:"Ha shares Jeem's base form but carries no dot. The open, undotted form gives it a cleaner presence. Precise bowl execution defines this letter.", strokes:["Begin from upper right as with Jeem","Execute the bowl with smooth, continuous motion","The entry and exit strokes should feel unified","The descending tail arcs gracefully below the baseline","No dot is added — the open form defines Ha"], proportionTip:"Ha and Jeem share identical proportions. Practice both together to feel how the dot changes each letter's visual weight.", forms:{isolated:"ح",initial:"حـ",medial:"ـحـ",final:"ـح"} }},
    { arabic:"خ", name:"Kha", roman:"kh", detail:{ arabicName:"خاء", globalIndex:7, nibAngle:"40°", about:"Kha is Ha with a single dot above. The dot placement above the bowl changes the letter's sound and visual weight. Consistent dot sizing and centering are essential.", strokes:["Draw the identical bowl form as Ha","Lift the pen after completing the base letter","Place a single dot centered above the bowl's peak","The dot should not touch the letter's body","Size the dot consistently with other dotted letters"], proportionTip:"The dot sits one dot-width above the peak of the bowl. Align it with the letter's visual center axis.", forms:{isolated:"خ",initial:"خـ",medial:"ـخـ",final:"ـخ"} }},
  ],
};
