import type { LetterGroup } from "./types";
export const group06: LetterGroup = {
  num:"06", name:"Fa, Qaf, Kaf", label:"FA GROUP", trait:"Circular heads", available:false,
  letters: [
    { arabic:"ف", name:"Fa", roman:"f", detail:{ arabicName:"فاء", globalIndex:20, nibAngle:"40°", about:"Fa features a distinctive round head above a horizontal base. The circular loop and its placement above the body require a confident, fluid circular stroke.", strokes:["Begin by drawing a circular loop at the upper right","The circle should close cleanly on itself","Drop down from the circle into the connecting base","Draw the base stroke extending to the left","Place a single dot above the circular head"], proportionTip:"Fa's circular head has a diameter of about 2 rhombic dots. It sits centered above the letter's body connection point.", forms:{isolated:"ف",initial:"فـ",medial:"ـفـ",final:"ـف"} }},
    { arabic:"ق", name:"Qaf", roman:"q", detail:{ arabicName:"قاف", globalIndex:21, nibAngle:"40°", about:"Qaf is one of the most complex letters in Thuluth, combining a circular body with a deep descender below the baseline. Two dots above complete its distinctive form.", strokes:["Draw a wide circular or oval body","The body sits above and descends below the baseline","The descender curves to the right below the baseline","Lift the pen and place two dots above the body","The two dots sit side by side, centered above the oval"], proportionTip:"Qaf's descender drops 3 rhombic dots below the baseline. The two dots above are evenly spaced — one dot-width apart.", forms:{isolated:"ق",initial:"قـ",medial:"ـقـ",final:"ـق"} }},
    { arabic:"ك", name:"Kaf", roman:"k", detail:{ arabicName:"كاف", globalIndex:22, nibAngle:"40°", about:"Kaf has a tall ascender with a distinctive interior diagonal stroke. In Thuluth, the letter's vertical height and the precision of its internal line are hallmarks of mastery.", strokes:["Draw the tall vertical ascender from top down","Form the curved base connecting to the right","Lift the pen and draw the small diagonal stroke inside the letter","The interior stroke sits in the upper portion of the body","Exit with a connecting stroke or serif at the base"], proportionTip:"Kaf's ascender equals Alif's height — 7 rhombic dots. The internal diagonal stroke sits at approximately 2/3 of the ascender's height.", forms:{isolated:"ك",initial:"كـ",medial:"ـكـ",final:"ـك"} }},
  ],
};
