import type { LetterGroup } from "./types";
export const group05: LetterGroup = {
  num:"05", name:"Tah, Dhah, Ain, Ghain", label:"TAH GROUP", trait:"Vertical ascenders & bowls", available:false,
  letters: [
    { arabic:"ط", name:"Tah", roman:"ṭ", detail:{ arabicName:"طاء", globalIndex:16, nibAngle:"40°", about:"Tah is an emphatic letter combining a tall vertical stroke with a wide horizontal base. The interplay of vertical and horizontal in Thuluth creates a powerful, monumental feel.", strokes:["Draw a wide curved base stroke from right to left","Without lifting, curve up into a tall vertical ascender","The ascender should echo the Alif's height and curve","Return to finish the base with a connecting exit","The letter should read as one unified, confident shape"], proportionTip:"Tah's vertical ascender should match Alif's height — 7 rhombic dots. The base spans 4–5 dots in width.", forms:{isolated:"ط",initial:"طـ",medial:"ـطـ",final:"ـط"} }},
    { arabic:"ظ", name:"Dhah", roman:"ẓ", detail:{ arabicName:"ظاء", globalIndex:17, nibAngle:"40°", about:"Dhah is Tah with a dot above the ascender. Placing the dot on a tall letter requires careful return movement — the ascender must be clean and upright to receive it.", strokes:["Draw the complete Tah form","Lift the pen at the ascender's top","Place a single dot above the ascender's tip","The dot must be centered on the vertical stroke","Maintain the dot's size relative to the letter's scale"], proportionTip:"The dot hovers one dot-width above Tah's ascender tip, centered on its vertical axis — it should crown, not clutter.", forms:{isolated:"ظ",initial:"ظـ",medial:"ـظـ",final:"ـظ"} }},
    { arabic:"ع", name:"Ain", roman:"ʿ", detail:{ arabicName:"عين", globalIndex:18, nibAngle:"40°", about:"Ain is one of Arabic's most distinctive sounds and shapes. Its open eye form — a curved body with a descending tail — is deeply characteristic of Thuluth's expressive vocabulary.", strokes:["Begin with a small curved hook at the top","Open into the eye-shaped body, curving left","The body should be open and airy, not closed","Transition into a descending stroke below the baseline","The tail sweeps gracefully downward and to the right"], proportionTip:"Ain's open 'eye' is its defining feature. The opening at the top should be about 2 dot-widths — enough to feel visually breathable.", forms:{isolated:"ع",initial:"عـ",medial:"ـعـ",final:"ـع"} }},
    { arabic:"غ", name:"Ghain", roman:"gh", detail:{ arabicName:"غين", globalIndex:19, nibAngle:"40°", about:"Ghain is Ain with a dot above the eye. The dot placement above an already complex form requires spatial awareness — it must float above without visually merging with the body.", strokes:["Draw the complete Ain form","Lift the pen after the descending tail","Return to position above the letter's body","Place a single dot above the eye opening","The dot should be visually distinct from the curved body below"], proportionTip:"Ghain's dot sits one dot-width above Ain's upper curve. Center it horizontally on the eye opening.", forms:{isolated:"غ",initial:"غـ",medial:"ـغـ",final:"ـغ"} }},
  ],
};
