import type { LetterGroup } from "./types";
export const group07: LetterGroup = {
  num:"07", name:"Lam, Meem, Noon, Ha", label:"LAM GROUP", trait:"Verticals, circles & curves", available:false,
  letters: [
    { arabic:"ل", name:"Lam", roman:"l", detail:{ arabicName:"لام", globalIndex:23, nibAngle:"40°", about:"Lam is a tall letter with a curved descent. Its elegant transition from a vertical entry into a sweeping leftward base makes it one of Thuluth's most graceful letters.", strokes:["Begin with a tall, slightly curved vertical stroke","Transition smoothly into the descending base","The curve should flow without any angular breaks","The base extends to the left as a connecting stroke","In isolation, finish with a gentle serif or hook"], proportionTip:"Lam's height matches the Alif at 7 rhombic dots. The curve from vertical to horizontal should be gradual — never abrupt.", forms:{isolated:"ل",initial:"لـ",medial:"ـلـ",final:"ـل"} }},
    { arabic:"م", name:"Meem", roman:"m", detail:{ arabicName:"ميم", globalIndex:24, nibAngle:"40°", about:"Meem has a distinctive round head with a descending tail below the baseline. The small circular body and elegant tail make it one of the most frequently drawn letters.", strokes:["Draw a small tight circle for the letter's head","The circle should close cleanly and feel complete","Extend a tail descending below the baseline to the left","The tail curves gracefully as it descends","In connected forms, join from the right before forming the circle"], proportionTip:"Meem's circular head is approximately 1.5 rhombic dots in diameter. The tail descends 2 dots below the baseline.", forms:{isolated:"م",initial:"مـ",medial:"ـمـ",final:"ـم"} }},
    { arabic:"ن", name:"Noon", roman:"n", detail:{ arabicName:"نون", globalIndex:25, nibAngle:"40°", about:"Noon shares the base form with Ba but features a dot inside its bowl. The concave base and single internal dot make Noon one of the most beautiful letters in the alphabet.", strokes:["Draw a concave curved base stroke","The curve should be deeper than Ba's — more bowl-like","The ends rise slightly on each side","Lift the pen and place a single dot centered inside the bowl","The dot should sit within the curve, not above it"], proportionTip:"Noon's dot sits inside its bowl, centered both horizontally and vertically within the concave space.", forms:{isolated:"ن",initial:"نـ",medial:"ـنـ",final:"ـن"} }},
    { arabic:"ه", name:"Ha", roman:"h", detail:{ arabicName:"هاء", globalIndex:26, nibAngle:"40°", about:"Ha has one of the most variable forms in Arabic, changing significantly across positions in a word. In Thuluth, each positional form is itself a study in curve and balance.", strokes:["In isolation, draw two overlapping loops","The upper loop is smaller than the lower","Both loops should close cleanly","Maintain consistent ink pressure through each curve","The letter's form shifts in connected positions — study each separately"], proportionTip:"Ha's isolated form spans about 3 rhombic dots. When connected, its forms compress and adapt — each must be practiced individually.", forms:{isolated:"ه",initial:"هـ",medial:"ـهـ",final:"ـه"} }},
  ],
};
