import type { LetterGroup } from "./types";
export const group04: LetterGroup = {
  num:"04", name:"Seen, Sheen, Saad, Dhad", label:"SEEN GROUP", trait:"Toothed & looped", available:false,
  letters: [
    { arabic:"س", name:"Seen", roman:"s", detail:{ arabicName:"سين", globalIndex:12, nibAngle:"40°", about:"Seen is characterized by its three distinctive teeth — small upward strokes — followed by a wide curved body. The rhythm of the teeth is essential to the letter's identity.", strokes:["Begin from the right with the first small tooth stroke","Draw the second tooth at equal height and spacing","Add the third tooth, maintaining consistent rhythm","Curve the base stroke leftward into the body","Finish with a connecting exit or final serif"], proportionTip:"Seen's three teeth are equally spaced and equal in height — about 1.5 dot-widths each. The total width spans 6–7 rhombic dots.", forms:{isolated:"س",initial:"سـ",medial:"ـسـ",final:"ـس"} }},
    { arabic:"ش", name:"Sheen", roman:"sh", detail:{ arabicName:"شين", globalIndex:13, nibAngle:"40°", about:"Sheen shares Seen's toothed base but adds three dots above in a triangle. The dots must not crowd the teeth — spacing is everything in this letter.", strokes:["Draw the three teeth as in Seen","Complete the base body stroke","Lift the pen and position above the teeth","Place two dots side by side above the teeth","Add a third dot centered above the pair, forming a triangle"], proportionTip:"Sheen's dots sit above the teeth, not above the body's curve. They should feel light and elevated, never crowding the strokes below.", forms:{isolated:"ش",initial:"شـ",medial:"ـشـ",final:"ـش"} }},
    { arabic:"ص", name:"Saad", roman:"ṣ", detail:{ arabicName:"صاد", globalIndex:14, nibAngle:"40°", about:"Saad is an emphatic letter with a large loop and a connected Waw-like tail. The wide oval body and sweeping tail make it one of Thuluth's most expressive letters.", strokes:["Enter from upper right with a curved stroke","Form a wide, oval loop closing on itself","Exit to the right with a connecting stroke","Draw the small hook or Waw-tail on the right side","The whole letter should feel open and expansive"], proportionTip:"Saad's oval body spans 5–6 rhombic dots in width. The interior of the loop should feel spacious — not cramped.", forms:{isolated:"ص",initial:"صـ",medial:"ـصـ",final:"ـص"} }},
    { arabic:"ض", name:"Dhad", roman:"ḍ", detail:{ arabicName:"ضاد", globalIndex:15, nibAngle:"40°", about:"Dhad shares Saad's base form with an additional dot above. This is one of the rarest sounds in world languages — unique to Arabic — and its letter carries that distinction.", strokes:["Draw the complete Saad base form","Lift the pen cleanly","Position above the letter's upper-right area","Place a single dot above the body's upper curve","Center the dot with the letter's visual axis"], proportionTip:"Dhad's dot sits above the upper-right of the oval body, one dot-width clear of the letter. It marks the letter without crowding it.", forms:{isolated:"ض",initial:"ضـ",medial:"ـضـ",final:"ـض"} }},
  ],
};
