import type { LetterGroup } from "./types";
export const group01: LetterGroup = {
  num:"01", name:"Alif, Ba, Ta, Tha", label:"ALIF GROUP", trait:"Vertical stem & base", available:true,
  letters: [
    { arabic:"ا", name:"Alif", roman:"ā / a", detail:{ arabicName:"ألف", globalIndex:1, nibAngle:"40°", about:"The first letter of the Arabic alphabet. In Thuluth, it is a tall, elegant vertical stroke with a subtle curve at the top and a graceful serif at the base.", strokes:["Start from the top with a thick entry stroke angled at 30°","Draw a tall, slightly curved vertical line downward","The height should be 7 dots (rhombic dots from the pen nib)","End with a gentle serif curving slightly to the left","Maintain consistent pressure throughout the stroke"], proportionTip:"The Alif is the measuring unit in Thuluth — all other letters are proportioned relative to it. Its height equals 7 rhombic dots stacked vertically.", forms:{isolated:"ا",initial:"ا",medial:"ـا",final:"ـا"} }},
    { arabic:"ب", name:"Ba", roman:"b", detail:{ arabicName:"باء", globalIndex:2, nibAngle:"40°", about:"The second letter forms the foundation of a family sharing the same base shape. Its elegant horizontal stroke and single dot below define the Ba family's character in Thuluth.", strokes:["Begin with a thin entry stroke from the right side","Draw a long, slightly curved horizontal base stroke to the left","The curve should be smooth and elegant, never flat or stiff","Form connecting hooks on each end at equal depth","Place a single dot precisely below the center of the letter body"], proportionTip:"Ba's width spans approximately 5 rhombic dots. The dot sits exactly one dot-width below the base of the letter's lowest point.", forms:{isolated:"ب",initial:"بـ",medial:"ـبـ",final:"ـب"} }},
    { arabic:"ت", name:"Ta", roman:"t", detail:{ arabicName:"تاء", globalIndex:3, nibAngle:"40°", about:"Ta shares the same base form as Ba but is distinguished by two dots placed symmetrically above the body. The alignment and spacing of these dots is critical to the letter's elegance.", strokes:["Draw the base stroke identically to Ba","Lift the pen and position above the letter's center","Place the first dot above-left of center","Place the second dot mirrored to the right at identical height","Ensure both dots are equal in size, angle, and spacing"], proportionTip:"The two dots sit one dot-width above the letter's body and are spaced one rhombic dot-width apart from each other.", forms:{isolated:"ت",initial:"تـ",medial:"ـتـ",final:"ـت"} }},
    { arabic:"ث", name:"Tha", roman:"th", detail:{ arabicName:"ثاء", globalIndex:4, nibAngle:"40°", about:"Tha completes the Ba family with three dots arranged in a triangle above the base. The triangular dot formation requires precision — any misalignment breaks the letter's harmony.", strokes:["Draw the same base stroke as Ba and Ta","Place two dots side by side above the letter body","Add a third dot centered above the first two","All three should form a balanced equilateral triangle","Maintain perfectly consistent size across all three dots"], proportionTip:"Three dots form a triangle: two on the bottom, one on top. The bottom pair aligns with the top edge of the letter body.", forms:{isolated:"ث",initial:"ثـ",medial:"ـثـ",final:"ـث"} }},
  ],
};
