import type { LetterGroup } from "./types";
export const group03: LetterGroup = {
  num:"03", name:"Dal, Dhal, Ra, Zay", label:"DAL GROUP", trait:"Non-connecting curves", available:false,
  letters: [
    { arabic:"د", name:"Dal", roman:"d", detail:{ arabicName:"دال", globalIndex:8, nibAngle:"45°", about:"Dal is a non-connecting letter with a simple angled stroke. Despite its apparent simplicity, achieving the correct angle and tail in Thuluth requires careful practice.", strokes:["Begin with a short angled entry from upper right","Draw the diagonal body stroke downward to the left","The angle should sit at approximately 45°","Finish with a small rightward serif at the base","Keep the stroke firm and decisive — Dal is sharp, not soft"], proportionTip:"Dal's width equals about 3 rhombic dots. The angle of the body is critical — too steep or too shallow changes the letter's identity.", forms:{isolated:"د",initial:"د",medial:"ـد",final:"ـد"} }},
    { arabic:"ذ", name:"Dhal", roman:"dh", detail:{ arabicName:"ذال", globalIndex:9, nibAngle:"45°", about:"Dhal is Dal with a dot above. A non-connecting letter, its dot must be placed precisely above the vertex of the angle to maintain proportion.", strokes:["Draw the identical body stroke as Dal","Lift the pen cleanly after the serif","Place a single dot above the letter's highest point","Center the dot directly above the body's apex","Ensure dot size matches other dotted letters in your script"], proportionTip:"The dot sits one dot-width above Dal's apex. Its horizontal center aligns with the letter's visual midpoint.", forms:{isolated:"ذ",initial:"ذ",medial:"ـذ",final:"ـذ"} }},
    { arabic:"ر", name:"Ra", roman:"r", detail:{ arabicName:"راء", globalIndex:10, nibAngle:"40°", about:"Ra is a non-connecting letter with a graceful descending curve below the baseline. In Thuluth, this curve is one of the most expressive strokes in the alphabet.", strokes:["Begin with a subtle curved entry from the right","Draw the short curved body above the baseline","Transition smoothly into the descending tail","The tail curves below the baseline in a gentle arc","Maintain consistent ink flow through the entire curve"], proportionTip:"Ra's descender reaches 2–3 rhombic dots below the baseline. The curve's elegance lies in its unbroken continuity.", forms:{isolated:"ر",initial:"ر",medial:"ـر",final:"ـر"} }},
    { arabic:"ز", name:"Zay", roman:"z", detail:{ arabicName:"زاي", globalIndex:11, nibAngle:"40°", about:"Zay is Ra with a dot above. The dot's placement above the curve requires a clean pen lift and precise positioning without disturbing the letter's flow.", strokes:["Execute the complete Ra stroke first","Lift the pen smoothly at the end","Return above the letter's body entry point","Place a single dot above the curve's highest point","The dot should balance visually above Ra's subtle peak"], proportionTip:"Zay's dot sits centered above the letter's body, one dot-width above its highest point. It should feel weightless, not heavy.", forms:{isolated:"ز",initial:"ز",medial:"ـز",final:"ـز"} }},
  ],
};
